COUNTRYCODE2REGION = {"AFG": "South Asia",
                      "ALB": "South East Europe",
                      "DZA": "Northern Africa",
                      "ASM": "Pacific",
                      "AND": "South West Europe",
                      "AGO": "Southern Africa",
                      "AIA": "West Indies",
                      "ATG": "West Indies",
                      "ARG": "South America",
                      "ARM": "South West Asia",
                      "ABW": "West Indies",
                      "AUS": "Pacific",
                      "AUT": "Central Europe",
                      "AZE": "South West Asia",
                      "BHS": "West Indies",
                      "BHR": "South West Asia",
                      "BGD": "South Asia",
                      "BRB": "West Indies",
                      "BLR": "Eastern Europe",
                      "BEL": "Western Europe",
                      "BLZ": "Central America",
                      "BEN": "Western Africa",
                      "BMU": "West Indies",
                      "BTN": "South Asia",
                      "BOL": "South America",
                      "BIH": "South East Europe",
                      "BWA": "Southern Africa",
                      "BRA": "South America",
                      "VGB": "West Indies",
                      "BRN": "South East Asia",
                      "BGR": "South East Europe",
                      "BFA": "Western Africa",
                      "BDI": "Central Africa",
                      "KHM": "South East Asia",
                      "CMR": "Western Africa",
                      "CAN": "North America",
                      "CPV": "Western Africa",
                      "CYM": "West Indies",
                      "CAF": "Central Africa",
                      "TCD": "Central Africa",
                      "CHL": "South America",
                      "CHN": "East Asia",
                      "CXR": "South East Asia",
                      "CCK": "South East Asia",
                      "COL": "South America",
                      "COM": "Indian Ocean",
                      "COG": "Central Africa",
                      "COK": "Pacific",
                      "CRI": "Central America",
                      "CIV": "Western Africa",
                      "HRV": "South East Europe",
                      "CUB": "West Indies",
                      "CYP": "South West Asia",
                      "CZE": "Central Europe",
                      "DNK": "Northern Europe",
                      "DJI": "Eastern Africa",
                      "DMA": "West Indies",
                      "DOM": "West Indies",
                      "ECU": "South America",
                      "EGY": "Northern Africa",
                      "SLV": "Central America",
                      "GNQ": "Western Africa",
                      "ERI": "Eastern Africa",
                      "EST": "Eastern Europe",
                      "ETH": "Eastern Africa",
                      "FLK": "South America",
                      "FRO": "Northern Europe",
                      "FJI": "Pacific",
                      "FIN": "Northern Europe",
                      "FRA": "Western Europe",
                      "GUF": "South America",
                      "PYF": "Pacific",
                      "GAB": "Western Africa",
                      "GMB": "Western Africa",
                      "GEO": "South West Asia",
                      "DEU": "Western Europe",
                      "GHA": "Western Africa",
                      "GIB": "South West Europe",
                      "GRC": "South East Europe",
                      "GRL": "North America",
                      "GRD": "West Indies",
                      "GLP": "West Indies",
                      "GUM": "Pacific",
                      "GTM": "Central America",
                      "--": "Western Europe",
                      "GIN": "Western Africa",
                      "GNB": "Western Africa",
                      "GUY": "South America",
                      "HTI": "West Indies",
                      "VAT": "Southern Europe",
                      "HND": "Central America",
                      "HUN": "Central Europe",
                      "ISL": "Northern Europe",
                      "IND": "South Asia",
                      "IDN": "South East Asia",
                      "IRN": "South West Asia",
                      "IRQ": "South West Asia",
                      "IRL": "Western Europe",
                      "ISR": "South West Asia",
                      "ITA": "Southern Europe",
                      "JAM": "West Indies",
                      "--": "Northern Europe",
                      "JPN": "East Asia",
                      "--": "Western Europe",
                      "JOR": "South West Asia",
                      "KAZ": "Central Asia",
                      "KEN": "Eastern Africa",
                      "KIR": "Pacific",
                      "PRK": "East Asia",
                      "KOR": "East Asia",
                      "KWT": "South West Asia",
                      "KGZ": "Central Asia",
                      "LAO": "South East Asia",
                      "LVA": "Eastern Europe",
                      "LBN": "South West Asia",
                      "LSO": "Southern Africa",
                      "LBR": "Western Africa",
                      "LBY": "Northern Africa",
                      "LIE": "Central Europe",
                      "LTU": "Eastern Europe",
                      "LUX": "Western Europe",
                      "MKD": "South East Europe",
                      "MDG": "Indian Ocean",
                      "MWI": "Southern Africa",
                      "MYS": "South East Asia",
                      "MDV": "South Asia",
                      "MLI": "Western Africa",
                      "MLT": "Southern Europe",
                      "--": "Western Europe",
                      "MHL": "Pacific",
                      "MTQ": "West Indies",
                      "MRT": "Western Africa",
                      "MUS": "Indian Ocean",
                      "MYT": "Indian Ocean",
                      "MEX": "Central America",
                      "FSM": "Pacific",
                      "MDA": "Eastern Europe",
                      "MCO": "Western Europe",
                      "MNG": "Northern Asia",
                      "MSR": "West Indies",
                      "MAR": "Northern Africa",
                      "MOZ": "Southern Africa",
                      "MMR": "South East Asia",
                      "NAM": "Southern Africa",
                      "NRU": "Pacific",
                      "NPL": "South Asia",
                      "NLD": "Western Europe",
                      "ANT": "West Indies",
                      "NCL": "Pacific",
                      "NZL": "Pacific",
                      "NIC": "Central America",
                      "NER": "Western Africa",
                      "NGA": "Western Africa",
                      "NIU": "Pacific",
                      "NFK": "Pacific",
                      "MNP": "Pacific",
                      "NOR": "Northern Europe",
                      "OMN": "South West Asia",
                      "PAK": "South Asia",
                      "PLW": "Pacific",
                      "--": "South West Asia",
                      "PAN": "Central America",
                      "PNG": "Pacific",
                      "PRY": "South America",
                      "PER": "South America",
                      "PHL": "South East Asia",
                      "PCN": "Pacific",
                      "POL": "Eastern Europe",
                      "PRT": "South West Europe",
                      "PRI": "West Indies",
                      "QAT": "South West Asia",
                      "REU": "Indian Ocean",
                      "ROM": "South East Europe",
                      "RUS": "Northern Asia",
                      "RWA": "Central Africa",
                      "KNA": "West Indies",
                      "LCA": "West Indies",
                      "SPM": "North America",
                      "VCT": "West Indies",
                      "SMR": "Southern Europe",
                      "STP": "Western Africa",
                      "SAU": "South West Asia",
                      "SEN": "Western Africa",
                      "--": "South East Europe",
                      "SYC": "Indian Ocean",
                      "SLE": "Western Africa",
                      "SGP": "South East Asia",
                      "SVK": "Central Europe",
                      "SVN": "South East Europe",
                      "SLB": "Pacific",
                      "SOM": "Eastern Africa",
                      "ZAF": "Southern Africa",
                      "ESP": "South West Europe",
                      "LKA": "South Asia",
                      "SDN": "Northern Africa",
                      "SUR": "South America",
                      "SJM": "Northern Europe",
                      "SWZ": "Southern Africa",
                      "SWE": "Northern Europe",
                      "CHE": "Central Europe",
                      "SYR": "South West Asia",
                      "TWN": "East Asia",
                      "TJK": "Central Asia",
                      "TZA": "Eastern Africa",
                      "THA": "South East Asia",
                      "TGO": "Western Africa",
                      "TKL": "Pacific",
                      "TON": "Pacific",
                      "TTO": "West Indies",
                      "TUN": "Northern Africa",
                      "TUR": "South West Asia",
                      "TKM": "Central Asia",
                      "TCA": "West Indies",
                      "TUV": "Pacific",
                      "UGA": "Eastern Africa",
                      "UKR": "Eastern Europe",
                      "ARE": "South West Asia",
                      "GBR": "Western Europe",
                      "USA": "North America",
                      "URY": "South America",
                      "UZB": "Central Asia",
                      "VUT": "Pacific",
                      "VEN": "South America",
                      "VNM": "South East Asia",
                      "VIR": "West Indies",
                      "WLF": "Pacific",
                      "ESH": "Northern Africa",
                      "WSM": "Pacific",
                      "YEM": "South West Asia",
                      "ZAR": "Central Africa",
                      "ZWB": "Southern Africa",
                      "ZWE": "Southern Africa"}

COUNTRYCODE2CONT = {"AFG": "Asia",
                    "ALB": "Europe",
                    "DZA": "Africa",
                    "ASM": "Oceania",
                    "AND": "Europe",
                    "AGO": "Africa",
                    "AIA": "Americas",
                    "ATG": "Americas",
                    "ARG": "Americas",
                    "ARM": "Asia",
                    "ABW": "Americas",
                    "AUS": "Oceania",
                    "AUT": "Europe",
                    "AZE": "Asia",
                    "BHS": "Americas",
                    "BHR": "Asia",
                    "BGD": "Asia",
                    "BRB": "Americas",
                    "BLR": "Europe",
                    "BEL": "Europe",
                    "BLZ": "Americas",
                    "BEN": "Africa",
                    "BMU": "Americas",
                    "BTN": "Asia",
                    "BOL": "Americas",
                    "BIH": "Europe",
                    "BWA": "Africa",
                    "BRA": "Americas",
                    "VGB": "Americas",
                    "BRN": "Asia",
                    "BGR": "Europe",
                    "BFA": "Africa",
                    "BDI": "Africa",
                    "KHM": "Asia",
                    "CMR": "Africa",
                    "CAN": "Americas",
                    "CPV": "Africa",
                    "CYM": "Americas",
                    "CAF": "Africa",
                    "TCD": "Africa",
                    "CHL": "Americas",
                    "CHN": "Asia",
                    "CXR": "Asia",
                    "CCK": "Asia",
                    "COL": "Americas",
                    "COM": "Africa",
                    "COG": "Africa",
                    "COK": "Oceania",
                    "CRI": "Americas",
                    "CIV": "Africa",
                    "HRV": "Europe",
                    "CUB": "Americas",
                    "CYP": "Asia",
                    "CZE": "Europe",
                    "DNK": "Europe",
                    "DJI": "Africa",
                    "DMA": "Americas",
                    "DOM": "Americas",
                    "ECU": "Americas",
                    "EGY": "Africa",
                    "SLV": "Americas",
                    "GNQ": "Africa",
                    "ERI": "Africa",
                    "EST": "Europe",
                    "ETH": "Africa",
                    "FLK": "Americas",
                    "FRO": "Europe",
                    "FJI": "Oceania",
                    "FIN": "Europe",
                    "FRA": "Europe",
                    "GUF": "Americas",
                    "PYF": "Oceania",
                    "GAB": "Africa",
                    "GMB": "Africa",
                    "GEO": "Asia",
                    "DEU": "Europe",
                    "GHA": "Africa",
                    "GIB": "Europe",
                    "GRC": "Europe",
                    "GRL": "Americas",
                    "GRD": "Americas",
                    "GLP": "Americas",
                    "GUM": "Oceania",
                    "GTM": "Americas",
                    "--": "Europe",
                    "GIN": "Africa",
                    "GNB": "Africa",
                    "GUY": "Americas",
                    "HTI": "Americas",
                    "VAT": "Europe",
                    "HND": "Americas",
                    "HUN": "Europe",
                    "ISL": "Europe",
                    "IND": "Asia",
                    "IDN": "Asia",
                    "IRN": "Asia",
                    "IRQ": "Asia",
                    "IRL": "Europe",
                    "ISR": "Asia",
                    "ITA": "Europe",
                    "JAM": "Americas",
                    "--": "Europe",
                    "JPN": "Asia",
                    "--": "Europe",
                    "JOR": "Asia",
                    "KAZ": "Asia",
                    "KEN": "Africa",
                    "KIR": "Oceania",
                    "PRK": "Asia",
                    "KOR": "Asia",
                    "KWT": "Asia",
                    "KGZ": "Asia",
                    "LAO": "Asia",
                    "LVA": "Europe",
                    "LBN": "Asia",
                    "LSO": "Africa",
                    "LBR": "Africa",
                    "LBY": "Africa",
                    "LIE": "Europe",
                    "LTU": "Europe",
                    "LUX": "Europe",
                    "MKD": "Europe",
                    "MDG": "Africa",
                    "MWI": "Africa",
                    "MYS": "Asia",
                    "MDV": "Asia",
                    "MLI": "Africa",
                    "MLT": "Europe",
                    "--": "Europe",
                    "MHL": "Oceania",
                    "MTQ": "Americas",
                    "MRT": "Africa",
                    "MUS": "Africa",
                    "MYT": "Africa",
                    "MEX": "Americas",
                    "FSM": "Oceania",
                    "MDA": "Europe",
                    "MCO": "Europe",
                    "MNG": "Asia",
                    "MSR": "Americas",
                    "MAR": "Africa",
                    "MOZ": "Africa",
                    "MMR": "Asia",
                    "NAM": "Africa",
                    "NRU": "Oceania",
                    "NPL": "Asia",
                    "NLD": "Europe",
                    "ANT": "Americas",
                    "NCL": "Oceania",
                    "NZL": "Oceania",
                    "NIC": "Americas",
                    "NER": "Africa",
                    "NGA": "Africa",
                    "NIU": "Oceania",
                    "NFK": "Oceania",
                    "MNP": "Oceania",
                    "NOR": "Europe",
                    "OMN": "Asia",
                    "PAK": "Asia",
                    "PLW": "Oceania",
                    "--": "Asia",
                    "PAN": "Americas",
                    "PNG": "Oceania",
                    "PRY": "Americas",
                    "PER": "Americas",
                    "PHL": "Asia",
                    "PCN": "Oceania",
                    "POL": "Europe",
                    "PRT": "Europe",
                    "PRI": "Americas",
                    "QAT": "Asia",
                    "REU": "Africa",
                    "ROM": "Europe",
                    "RUS": "Asia",
                    "RWA": "Africa",
                    "KNA": "Americas",
                    "LCA": "Americas",
                    "SPM": "Americas",
                    "VCT": "Americas",
                    "SMR": "Europe",
                    "STP": "Africa",
                    "SAU": "Asia",
                    "SEN": "Africa",
                    "--": "Europe",
                    "SYC": "Africa",
                    "SLE": "Africa",
                    "SGP": "Asia",
                    "SVK": "Europe",
                    "SVN": "Europe",
                    "SLB": "Oceania",
                    "SOM": "Africa",
                    "ZAF": "Africa",
                    "ESP": "Europe",
                    "LKA": "Asia",
                    "SDN": "Africa",
                    "SUR": "Americas",
                    "SJM": "Europe",
                    "SWZ": "Africa",
                    "SWE": "Europe",
                    "CHE": "Europe",
                    "SYR": "Asia",
                    "TWN": "Asia",
                    "TJK": "Asia",
                    "TZA": "Africa",
                    "THA": "Asia",
                    "TGO": "Africa",
                    "TKL": "Oceania",
                    "TON": "Oceania",
                    "TTO": "Americas",
                    "TUN": "Africa",
                    "TUR": "Asia",
                    "TKM": "Asia",
                    "TCA": "Americas",
                    "TUV": "Oceania",
                    "UGA": "Africa",
                    "UKR": "Europe",
                    "ARE": "Asia",
                    "GBR": "Europe",
                    "USA": "Americas",
                    "URY": "Americas",
                    "UZB": "Asia",
                    "VUT": "Oceania",
                    "VEN": "Americas",
                    "VNM": "Asia",
                    "VIR": "Americas",
                    "WLF": "Oceania",
                    "ESH": "Africa",
                    "WSM": "Oceania",
                    "YEM": "Asia",
                    "ZAR": "Africa",
                    "ZWB": "Africa",
                    "ZWE": "Africa"}

REGIONS = ['Arab World',
           'Caribbean small states',
           'Central Europe and the Baltics',
           'Early-demographic dividend',
           'East Asia & Pacific',
           'East Asia & Pacific (excluding high income)',
           'East Asia & Pacific (IDA & IBRD countries)',
           'Euro area',
           'Europe & Central Asia',
           'Europe & Central Asia (excluding high income)',
           'Europe & Central Asia (IDA & IBRD countries)',
           'European Union',
           'Fragile and conflict affected situations',
           'Heavily indebted poor countries (HIPC)',
           'High income',
           'IBRD only',
           'IDA & IBRD total',
           'IDA blend',
           'IDA only',
           'IDA total',
           'Late-demographic dividend',
           'Latin America & Caribbean',
           'Latin America & Caribbean (excluding high income)',
           'Latin America & the Caribbean (IDA & IBRD countries)',
           'Least developed countries: UN classification',
           'Low & middle income',
           'Low income',
           'Lower middle income',
           'Middle East & North Africa',
           'Middle East & North Africa (excluding high income)',
           'Middle East & North Africa (IDA & IBRD countries)',
           'Middle income',
           'North America',
           'Not classified',
           'OECD members',
           'Other small states',
           'Pacific island small states',
           'Post-demographic dividend',
           'Pre-demographic dividend',
           'Small states',
           'South Asia',
           'South Asia (IDA & IBRD)',
           'Sub-Saharan Africa',
           'Sub-Saharan Africa (excluding high income)',
           'Sub-Saharan Africa (IDA & IBRD countries)',
           'Upper middle income',
           'World']

countries = ["Afghanistan",
             "Albania",
             "Algeria",
             "American Samoa",
             "Andorra",
             "Angola",
             "Antigua and Barbuda",
             "Argentina",
             "Armenia",
             "Aruba",
             "Australia",
             "Austria",
             "Azerbaijan",
             "Bahamas,The",
             "Bahrain",
             "Bangladesh",
             "Barbados",
             "Belarus",
             "Belgium",
             "Belize",
             "Benin",
             "Bermuda",
             "Bhutan",
             "Bolivia",
             "Bosnia and Herzegovina",
             "Botswana",
             "Brazil",
             "British Virgin Islands",
             "Brunei Darussalam",
             "Bulgaria",
             "Burkina Faso",
             "Burundi",
             "Cabo Verde",
             "Cambodia",
             "Cameroon",
             "Canada",
             "Cayman Islands",
             "Central African Republic",
             "Chad",
             "Channel Islands",
             "Chile",
             "China",
             "Colombia",
             "Comoros",
             "Congo,Dem. Rep.",
             "Congo,Rep.",
             "Costa Rica",
             "Cote d'Ivoire",
             "Croatia",
             "Cuba",
             "Curacao",
             "Cyprus",
             "Czech Republic",
             "Denmark",
             "Djibouti",
             "Dominica",
             "Dominican Republic",
             "Ecuador",
             "Egypt,Arab Rep.",
             "El Salvador",
             "Equatorial Guinea",
             "Eritrea",
             "Estonia",
             "Ethiopia",
             "Faroe Islands",
             "Fiji",
             "Finland",
             "France",
             "French Polynesia",
             "Gabon",
             "Gambia,The",
             "Georgia",
             "Germany",
             "Ghana",
             "Gibraltar",
             "Greece",
             "Greenland",
             "Grenada",
             "Guam",
             "Guatemala",
             "Guinea",
             "Guinea-Bissau",
             "Guyana",
             "Haiti",
             "Honduras",
             "Hong Kong SAR,China",
             "Hungary",
             "Iceland",
             "India",
             "Indonesia",
             "Iran,Islamic Rep.",
             "Iraq",
             "Ireland",
             "Isle of Man",
             "Israel",
             "Italy",
             "Jamaica",
             "Japan",
             "Jordan",
             "Kazakhstan",
             "Kenya",
             "Kiribati",
             "Korea,Dem. People’s Rep.",
             "Korea,Rep.",
             "Kosovo",
             "Kuwait",
             "Kyrgyz Republic",
             "Lao PDR",
             "Latvia",
             "Lebanon",
             "Lesotho",
             "Liberia",
             "Libya",
             "Liechtenstein",
             "Lithuania",
             "Luxembourg",
             "Macao SAR,China",
             "Macedonia,FYR",
             "Madagascar",
             "Malawi",
             "Malaysia",
             "Maldives",
             "Mali",
             "Malta",
             "Marshall Islands",
             "Mauritania",
             "Mauritius",
             "Mexico",
             "Micronesia,Fed. Sts.",
             "Moldova",
             "Monaco",
             "Mongolia",
             "Montenegro",
             "Morocco",
             "Mozambique",
             "Myanmar",
             "Namibia",
             "Nauru",
             "Nepal",
             "Netherlands",
             "New Caledonia",
             "New Zealand",
             "Nicaragua",
             "Niger",
             "Nigeria",
             "Northern Mariana Islands",
             "Norway",
             "Oman",
             "Pakistan",
             "Palau",
             "Panama",
             "Papua New Guinea",
             "Paraguay",
             "Peru",
             "Philippines",
             "Poland",
             "Portugal",
             "Puerto Rico",
             "Qatar",
             "Romania",
             "Russian Federation",
             "Rwanda",
             "Samoa",
             "San Marino",
             "Sao Tome and Principe",
             "Saudi Arabia",
             "Senegal",
             "Serbia",
             "Seychelles",
             "Sierra Leone",
             "Singapore",
             "Sint Maarten (Dutch part)",
             "Slovak Republic",
             "Slovenia",
             "Solomon Islands",
             "Somalia",
             "South Africa",
             "South Sudan",
             "Spain",
             "Sri Lanka",
             "St. Kitts and Nevis",
             "St. Lucia",
             "St. Martin (French part)",
             "St. Vincent and the Grenadines",
             "Sudan",
             "Suriname",
             "Swaziland",
             "Sweden",
             "Switzerland",
             "Syrian Arab Republic",
             "Tajikistan",
             "Tanzania",
             "Thailand",
             "Timor-Leste",
             "Togo",
             "Tonga",
             "Trinidad and Tobago",
             "Tunisia",
             "Turkey",
             "Turkmenistan",
             "Turks and Caicos Islands",
             "Tuvalu",
             "Uganda",
             "Ukraine",
             "United Arab Emirates",
             "United Kingdom",
             "United States",
             "Uruguay",
             "Uzbekistan",
             "Vanuatu",
             "Venezuela,RB",
             "Vietnam",
             "Virgin Islands (U.S.)",
             "West Bank and Gaza",
             "Yemen,Rep.",
             "Zambia",
             "Zimbabwe"]
